GET http://localhost:3456/todos
Accept: application/json

###
POST http://localhost:3456/todos
Content-Type: application/json

{
    "title": "Learn Vaadin",
    "completed": false
}

###
PUT http://localhost:3456/todos/12
Content-Type: application/json

{
  "title": "Learn Vaadin",
  "completed": true
}

###
DELETE http://localhost:3456/todos/12

###
POST http://localhost:3456/todos
Content-Type: application/x-www-form-urlencoded

title=Learn Thymeleaf&completed=false

###

###

GET https://swapi.dev/api/people/1/
Accept: application/json

###


GET http://localhost:3456/swapi/people/1/
Accept: application/json

###
